
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 59161088
 */
public class GamePage2 extends javax.swing.JFrame {

    /**
     * Creates new form GamePage2
     */
    public GamePage2() {
        initComponents();
        userchoose.setVisible(false);
        comchoose.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        funtion1 = new javax.swing.JButton();
        funtion2 = new javax.swing.JButton();
        funtion3 = new javax.swing.JButton();
        funtion4 = new javax.swing.JButton();
        comchoose = new javax.swing.JTextField();
        userchoose = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(591, 416));
        getContentPane().setLayout(null);

        jLabel1.setText("เลือกเพื่อเดาใจคอม");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 140, 40);

        jLabel2.setText("ด่านสอง");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 50, 80, 40);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 330, 73, 23);

        funtion1.setBackground(new java.awt.Color(255, 0, 51));
        funtion1.setForeground(new java.awt.Color(255, 0, 51));
        funtion1.setText("Red");
        funtion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funtion1ActionPerformed(evt);
            }
        });
        getContentPane().add(funtion1);
        funtion1.setBounds(50, 160, 100, 60);

        funtion2.setBackground(new java.awt.Color(0, 0, 204));
        funtion2.setForeground(new java.awt.Color(0, 0, 204));
        funtion2.setText("Blue");
        funtion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funtion2ActionPerformed(evt);
            }
        });
        getContentPane().add(funtion2);
        funtion2.setBounds(180, 160, 100, 60);

        funtion3.setBackground(new java.awt.Color(255, 255, 0));
        funtion3.setForeground(new java.awt.Color(255, 255, 0));
        funtion3.setText("Yellow");
        funtion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funtion3ActionPerformed(evt);
            }
        });
        getContentPane().add(funtion3);
        funtion3.setBounds(320, 160, 100, 60);

        funtion4.setBackground(new java.awt.Color(0, 204, 0));
        funtion4.setForeground(new java.awt.Color(0, 204, 0));
        funtion4.setText("Green");
        funtion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funtion4ActionPerformed(evt);
            }
        });
        getContentPane().add(funtion4);
        funtion4.setBounds(460, 160, 100, 60);

        comchoose.setEditable(false);
        comchoose.setEnabled(false);
        getContentPane().add(comchoose);
        comchoose.setBounds(430, 20, 110, 40);

        userchoose.setEditable(false);
        userchoose.setEnabled(false);
        getContentPane().add(userchoose);
        userchoose.setBounds(50, 30, 110, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StartPage start = new StartPage();
        int input = JOptionPane.showConfirmDialog(null, "ถ้าคุณกดกลับไปจะเริ่มเล่นใหม่ตั้งแต่แรก ยืนยันหรือไม่ ", "จะกลับไปหรืออยู่ต่อ",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null);
        if (input == 0) {
            dispose();
            start.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void funtion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funtion2ActionPerformed
        GamepageService.getBtn(2);
        GamepageService.setAnswer(5);
        GamepageService.getAnswerStateTwo();
    }//GEN-LAST:event_funtion2ActionPerformed

    private void funtion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funtion1ActionPerformed
        GamepageService.getBtn(2);
        GamepageService.setAnswer(4);
        GamepageService.getAnswerStateTwo();
    }//GEN-LAST:event_funtion1ActionPerformed

    private void funtion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funtion3ActionPerformed
       GamepageService.getBtn(2);
       GamepageService.setAnswer(6);
       GamepageService.getAnswerStateTwo();
    }//GEN-LAST:event_funtion3ActionPerformed

    private void funtion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funtion4ActionPerformed
        GamepageService.getBtn(2);
        GamepageService.setAnswer(7);
        GamepageService.getAnswerStateTwo();
    }//GEN-LAST:event_funtion4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField comchoose;
    public static javax.swing.JButton funtion1;
    public static javax.swing.JButton funtion2;
    public static javax.swing.JButton funtion3;
    public static javax.swing.JButton funtion4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField userchoose;
    // End of variables declaration//GEN-END:variables
}
