/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 59161088
 */
public class HowtoPlayPage extends javax.swing.JFrame {

    /**
     * Creates new form HowtoPlayPage
     */
    public HowtoPlayPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(516, 438));
        getContentPane().setLayout(null);

        jLabel1.setText("กติกาการเล่น");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 40, 130, 60);

        jLabel2.setText("..................................ขอให้โชคดี...................");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 260, 410, 30);

        jLabel3.setText("1. เราจะมีทั้งหมด 3 ด่าน จะต้องเล่นไปทีละด่านผ่านไปเรื่อยๆ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 370, 30);

        jLabel4.setText("2. ในด่านหนึ่งจะมีทั้งหมด 3 ตัวเลือกให้เลือกเพื่อเดาว่าคอมจะตอบอันไหน มีใบ้ให้");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 380, 30);

        jLabel5.setText("3. พอไปถึงด่านสอง จะมี สี่ตัวเลือกและคำใบ้");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 380, 30);

        jLabel6.setText("4. ด่านสุดท้ายมี สามตัวเลือกแต่ไม่มีคำใบ้ให้ โดยเราให้โอากาสสองครั้งในการทำให้ผ่าน");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 200, 410, 30);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 340, 70, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowtoPlayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowtoPlayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowtoPlayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowtoPlayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowtoPlayPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
